SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_gerente_propietario'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_informe'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_informacion_complementaria'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_asesor'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_asesor_especialidad'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_tarea'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_tipo_ingreso'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_tipo_egreso'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_horario'
AND TABLE_SCHEMA='bd_onboarding';

SELECT DISTINCT TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME= 'id_tipo_regimen'
AND TABLE_SCHEMA='bd_onboarding';